# Generated by Django 3.1.5 on 2021-03-01 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='song_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
