# Generated by Django 3.1.5 on 2021-03-01 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210114_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='curent_song',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
