# Generated by Django 3.1.5 on 2021-03-01 22:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_room_curent_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='curent_song',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
