# Generated by Django 3.1.5 on 2021-03-01 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210302_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='curent_song',
        ),
    ]
