# Generated by Django 3.1.5 on 2021-03-01 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_room_curent_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='curent_song',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
